### ISSUE TITLE
A 'how to use' and 'how to install' 

### ISSUE THREAD

**Issue by DanGeffroy** [NicolasThebaud/leafDB#1]
A 'how to use' and 'how to install' sections would be nice in the README.md :heart:

**Comment by NicolasThebaud** [comment]
Hi Dan,

I finally added those sections to the ReadMe (253f18ee97d56217668897baba3c90924935e8c3), I hope it suits your need.
Please know that I'm working on a front page for Leaf, that will include installation & usage tutorials.
In the meantime, you can still read those informations in the readme
